### ISSUE TITLE
504 error when ingest worked fine

### ISSUE THREAD

**Issue by kspurgin** [trln/spofford-client#5]
Not sure how much we care about such discrepancies, but I got this error:

```
aal:/mnt/c/code/spofford-client »spofford ingest ../data/argot/add_print1.json
[Spofford::Client::Packager] Here is the filenames thingy: {:source=>"../data/argot/add_print1.json", :zipname=>"add_print1.json"}
[Spofford::Client::Packager] First filename supplied is a zip, using that as ingest package
[Spofford::Client::DefaultClient] #<Net::HTTPGatewayTimeOut 504 Gateway Time-out readbody=true>
[Spofford::Client::DefaultClient] Failed request: 504 : Gateway Time-out
Ingest submission failed, false
```

Yet: the package went through and status is now Complete:
https://ingest.discovery.trln.org/transactions/48122

**Comment by adjam** [comment]
Closing this, due to the resolution being unclear and the issue not having recurred enough in three years to prompt further investigation.  In this situation, the client is correctly reporting that it encountered an error and particularly in the case of a timeout, there's no indication of what actually happened "on the other side." One key piece of information that will be missing in the response is the Transaction ID the client could have used in subsequent requests to see what happened to the submitted transaction.

In general, when your ingest process encounters an error a human will have to follow up on it.
